#!/usr/bin/env bash
# Generate an RS256 (RSA-2048) keypair for JWT signing AND populate .env.local
# with the minimum env required for native (npm run dev) development.
#
# Idempotent:
#   - skips key generation if JWT_PRIVATE_KEY already present in .env.local
#   - only appends DATABASE_URL / FE_ORIGIN / APP_ENV / NEXT_PUBLIC_API_BASE_URL
#     entries that are absent

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT}/.env.local"

# --- 1. Keys --------------------------------------------------------------
if [ -f "${ENV_FILE}" ] && grep -q '^JWT_PRIVATE_KEY=' "${ENV_FILE}"; then
  echo "i  ${ENV_FILE} already contains JWT_PRIVATE_KEY — skipping key generation."
else
  TMP_DIR="$(mktemp -d)"
  trap 'rm -rf "${TMP_DIR}"' EXIT

  openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 \
    -out "${TMP_DIR}/private.pem" 2>/dev/null
  openssl rsa -in "${TMP_DIR}/private.pem" -pubout \
    -out "${TMP_DIR}/public.pem" 2>/dev/null

  PRIV=$(awk '{printf "%s\\n", $0}' "${TMP_DIR}/private.pem")
  PUB=$(awk '{printf "%s\\n", $0}' "${TMP_DIR}/public.pem")

  {
    echo ""
    echo "# Generated by scripts/gen-keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "JWT_PRIVATE_KEY=\"${PRIV}\""
    echo "JWT_PUBLIC_KEY=\"${PUB}\""
  } >> "${ENV_FILE}"

  echo "OK  wrote JWT_PRIVATE_KEY + JWT_PUBLIC_KEY (RSA-2048 RS256) to ${ENV_FILE}"
fi

# --- 2. Dev env defaults --------------------------------------------------
touch "${ENV_FILE}"
add_if_missing() {
  local key="$1"
  local val="$2"
  if ! grep -q "^${key}=" "${ENV_FILE}"; then
    echo "${key}=${val}" >> "${ENV_FILE}"
    echo "OK  added ${key}=${val} to ${ENV_FILE}"
  fi
}

add_if_missing DATABASE_URL              "postgresql://app:app@localhost:5433/auth"
add_if_missing FE_ORIGIN                 "http://localhost:3000"
add_if_missing APP_ENV                   "dev"
add_if_missing LOG_LEVEL                 "info"
# NOTE: BE port defaults to 4000 in code. Do NOT export a global PORT in .env.local —
# `next dev` reads PORT too and would steal whichever the BE wants.
add_if_missing NEXT_PUBLIC_API_BASE_URL  "http://localhost:4000"

# --- 3. Frontend mirror ---------------------------------------------------
# Next.js auto-loads `apps/frontend/.env.local` when running `next dev`.
FE_ENV="${ROOT}/apps/frontend/.env.local"
if [ ! -f "${FE_ENV}" ]; then
  cat > "${FE_ENV}" <<EOF
# Generated by scripts/gen-keys.sh — Next.js auto-loads this on \`next dev\`.
NEXT_PUBLIC_API_BASE_URL=http://localhost:4000
EOF
  echo "OK  wrote ${FE_ENV}"
fi

echo ""
echo "Done. Next: \`npm run setup\` (once) then \`npm run dev\`."
